Make `githooks run` require the `--name` argument
Previously, not passing a hook name would result in trying to execute a hook named `None`:
```
githooks run
No hooks called None found. Add a [tool.githooks] section to your pyproject.toml with the desired hook
```
Now, this fails earlier with a more intuitive message:
```
 githooks run
Usage: githooks run [OPTIONS] [ARGS]...
Try 'githooks run --help' for help.

Error: Missing option '--name'.  Choose from:
	applypatch-msg,
	pre-applypatch,
	post-applypatch,
...
```